### ISSUE TITLE
Deploy to location other than C:/Apps

### ISSUE THREAD

**Issue by swcarter007** [TechnossusLLC/On-Premises-Release-Toolkit#1]
Is it possible to deploy to a configurable location other than the C:/App/Name?

**Comment by cwoolumtechnossus** [comment]
Would you like to be able to override base path or the entire path including the applications folder name?

**Comment by swcarter007** [comment]
Ideally it would be to override the entire path so that we could store them in a different location of our choosing.

**Comment by cwoolumtechnossus** [comment]
I've added the ability to override the path for the application. It's in the advanced section.
