### ISSUE TITLE
Bug: "installIfNotExists" checkbox in EnableWindowsService seems to have no effect

### ISSUE THREAD

**Issue by armingerten** [TechnossusLLC/On-Premises-Release-Toolkit#11]
Hi there! First of all: thanks for providing these tools for easily disabling/enabling/installing windows service from TFS on a remote system!

However, I am experiencing a strange behavior: When the checkbox "Install If Not Exists" is not enabled, the script seems to take the "Install path" anyway (Log says: "Installing the service.", "Using service account.", etc...). Unfortunately, when I did not specify a serviceAccountUser (I only wanted to disable/enable the service, but not install it), it then just deletes my service, which is exactly the opposite what I was trying to achieve! :-)

Can you have a look? I noticed you are passing the "installIfNotExists" as a string instead of a boolean - maybe this could already be the source of the bug?

Thanks in advance!

**Comment by cwoolumtechnossus** [comment]
Hey @armingerten, Let me take a look at it and figure out why that is happening! Unfortunately, VSTS passes boolean parameters as strings so I have to check if a flag is set to "false".

**Comment by armingerten** [comment]
Hey @cwoolumtechnossus, did you have the chance to have a look meanwhile? :-) 

Regarding the "Install If Not Exists" check-box: 

I managed to fix the issue by replacing EnableWindowsService.ps1:49 with the following code:
`if([System.Convert]::ToBoolean($installIfNotExists)){`

It is working fine for me (I am using TFS version 15.112.26307.0)... Could this be a viable fix?
