### ISSUE TITLE
request - add DisplayName, DependsOn, and StartupType inputs to EnableWindowsService

### ISSUE THREAD

**Issue by mikejramsey** [TechnossusLLC/On-Premises-Release-Toolkit#3]
Will you be releasing future updates to the EnableWindowsService task? 

I'd like to request adding the DisplayName, Description, DependsOn and StartupTypes as task inputs.

**Comment by cwoolumtechnossus** [comment]
Yes, I can add these early next week.

**Comment by cwoolumtechnossus** [comment]
I've released the new functionality. It rolls out with task version 1.4.0
