### ISSUE TITLE
What about advanced database deployment settings?

### ISSUE THREAD

**Issue by peder** [TechnossusLLC/On-Premises-Release-Toolkit#7]
Is there a way to change properties like "Exclude Views" or "Set Properties" from the deployment task?

**Comment by peder** [comment]
![image](https://cloud.githubusercontent.com/assets/1018574/17191291/eb225002-540e-11e6-9fa6-b73511a6cabb.png)

Specifically, I'm curious if we can use these settings with the database deployment task. I'm trying to stop the task from executing any `ALTER DATABASE` commands.

**Comment by cwoolumtechnossus** [comment]
Hi Peder, I can alter the task to accept a *.publish.xml file. You would be able to specify those advanced settings and any other overrides would be ignored. Would that work for you?

**Comment by peder** [comment]
I'm like 99% sure it would, and that probably is a relatively small change to the VSTS task (vs building in support for many or all of the options).

**Comment by cwoolumtechnossus** [comment]
Okay, I'll add the functionality in and test it. I'm thinking i can get it in today.

**Comment by cwoolumtechnossus** [comment]
Hi Peder, I've added a new checkbox and text field that lets you select a config file. I've tested it on one of my test projects and it worked. Let me know if this works for you. You will need to make sure your *publish.xml file is included in your build drops.

![image](https://cloud.githubusercontent.com/assets/16725244/17451250/44ff195e-5b1a-11e6-9401-2680ec0eb1b6.png)

**Comment by cwoolumtechnossus** [comment]
Marking as closed
